//Automatically generated by makefile, do not edit
.n64 // Let armips know we're coding for the N64 architecture
.open "rom/bk.z64", "rom/bk.mod.z64", 0 // Open the ROM file
.include "asm/symbols.asm" // Include ct2.asm to tell armips' linker where to find the game's function(s)
.close